export const roles = {
  member: {
    value: "member",
    name: "Member",
    description: "Full access to most resources",
    permissions: {
      project: {
        create: false,
        read: true,
        update: false,
        delete: false,
        list: false,
      },
      teamMembers: {
        create: false,
        read: true,
        update: false,
        delete: false,
        list: true,
      },
      apiKeys: {
        create: true,
        read: true,
        update: true,
        delete: false,
        list: true,
      },
      analytics: { read: true },
      logs: {
        create: true,
        read: true,
        update: true,
        delete: true,
        list: true,
        export: true,
      },
      users: {
        create: false,
        read: true,
        update: false,
        delete: false,
        list: true,
        export: true,
      },
      prompts: {
        create: true,
        read: true,
        update: true,
        delete: true,
        list: true,
        run: true,
      },
      radars: {
        create: true,
        read: true,
        update: true,
        delete: true,
        list: true,
      },
      datasets: {
        create: true,
        read: true,
        update: true,
        delete: true,
        list: true,
      },
      checklists: {
        create: true,
        read: true,
        update: true,
        delete: true,
        list: true,
      },
      evaluations: {
        create: true,
        read: true,
        update: true,
        delete: true,
        list: true,
        run: true,
      },
    },
  },
}
