name: Build and push ml image

on:
  release:
    types: [published]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the private ml repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          path: ml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "lunary/lunary"

      - name: Remove 'v' prefix from release tag
        id: release_tag
        run: echo "tag=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')" >> $GITHUB_OUTPUT

      - name: Build and push ml
        uses: docker/build-push-action@v5
        with:
          context: ml
          push: true
          tags: |
            lunary/ml:latest
            lunary/ml:${{ steps.release_tag.outputs.tag }}
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
